# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-29 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
        migrations.RemoveField(
            model_name='register',
            name='age',
        ),
        migrations.RemoveField(
            model_name='register',
            name='phone',
        ),
        migrations.AddField(
            model_name='register',
            name='dep',
            field=models.CharField(default='MCA', max_length=200),
        ),
        migrations.AddField(
            model_name='register',
            name='uid',
            field=models.CharField(default='12345', max_length=200),
        ),
        migrations.AddField(
            model_name='register',
            name='utype',
            field=models.CharField(default='HOD', max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(default='vis@gmail.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(default='vis', max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(default='vis', max_length=200),
        ),
    ]
