# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-29 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200629_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=200)),
                ('dep', models.CharField(max_length=200)),
            ],
        ),
    ]
