# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-29 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_results_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
