# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-30 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='mob',
            field=models.CharField(default='9874563210', max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
